<a href="https://colab.research.google.com/github/MohitS05/TelChurn/blob/master/Churn_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pprint
import csv
import pandas as pd
from pprint import pprint
from google.colab import drive
drive.mount('/content/gdrive')
dat= pd.read_csv('/content/gdrive/My Drive/Machine Learning Internship/TelecomChurnData.csv')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np

  from sklearn.preprocessing import LabelEncoder , OneHotEncoder

##Checking for NULL Values

In [0]:
def fixmisval():
  pass

In [0]:
if(dat.isnull().any().any()):
  print("Missing Values present")
  fixmisval()
else:
  print("No Missing Values present")
  

No Missing Values present


##Preparing Data for training

In [0]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [0]:
Id_col     = ['customerID']
target_col = ["Churn"]
cat_cols   = dat.nunique()[dat.nunique() < 6].keys().tolist()
cat_cols   = [x for x in cat_cols if x not in target_col]

num_cols   = [x for x in dat.columns if x not in cat_cols + target_col + Id_col]

bin_cols   = dat.nunique()[dat.nunique() == 2].keys().tolist()

multi_cols = [i for i in cat_cols if i not in bin_cols]

le = LabelEncoder()
for i in bin_cols :
    dat[i] = le.fit_transform(dat[i])
    
telcom = pd.get_dummies(data = dat,columns = multi_cols )

df_dat_og = dat.copy()
dat = dat.drop(columns = num_cols,axis = 1)


Putting Churn Column at end becuase it was creating some error if it was in middle 

In [0]:
cols = list(telcom.columns.values) #Make a list of all of the columns in the data
print(len(cols))
print(cols)
cols.pop(cols.index('Churn')) #Remove b from list
#cols.pop(cols.index('tenure')) #Remove x from list
telcom = telcom[cols+['Churn']]


42
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn', 'MultipleLines_No', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_DSL', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']


In [0]:
  y = telcom.iloc[:, 41].values
  X=telcom.iloc[:,1:40]

s w

###Some of the Data type were Text so changing them to numeric and then replacing missing values with Mean

In [0]:
X.at[488,'TotalCharges']=52.55

X['TotalCharges'] = pd.to_numeric(X['TotalCharges'],errors='coerce')

#X.at[488,'TotalCharges']=52.55
null_columns=X.columns[X.isnull().any()]
X[null_columns].isnull().sum()
print(X[X.isnull().any(axis=1)][null_columns].head())
print(X['TotalCharges'].mean())
X.at[753,'TotalCharges']=2282.98
X.at[936,'TotalCharges']=2282.98
X.at[1082,'TotalCharges']=2282.98
X.at[1340,'TotalCharges']=2282.98
X.at[3331,'TotalCharges']=2282.98
X.at[3826,'TotalCharges']=2282.98
X.at[4380,'TotalCharges']=2282.98
X.at[5218,'TotalCharges']=2282.98
X.at[6670,'TotalCharges']=2282.98
X.at[6754,'TotalCharges']=2282.98

#sze = X.shape[0]

#for i in range(sze):
# if(X.at[i,'TotalCharges']=='NULL'):
#   X.at[i,'TotalCharges'] = X[TotalCharges].mean()

Empty DataFrame
Columns: []
Index: []
2282.983252875199


##Split the data and run the algorithm

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)  
#pprint(X_train)

NameError: ignored

In [0]:
regressor = RandomForestClassifier(n_estimators=20, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test) 

In [0]:
print(y_pred)
print(y_test)

[0 0 0 ... 0 0 1]
[0 0 0 ... 0 1 0]


##Evaluating the results of Random Forest

In [0]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[3712  400]
 [ 824  699]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86      4112
           1       0.64      0.46      0.53      1523

    accuracy                           0.78      5635
   macro avg       0.73      0.68      0.70      5635
weighted avg       0.77      0.78      0.77      5635

0.7827861579414375


##For Descion tree

In [0]:
from sklearn.tree import DecisionTreeClassifier 

clf = DecisionTreeClassifier()

clf = clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

In [0]:

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[3364  748]
 [ 787  736]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.81      4112
           1       0.50      0.48      0.49      1523

    accuracy                           0.73      5635
   macro avg       0.65      0.65      0.65      5635
weighted avg       0.73      0.73      0.73      5635

0.7275953859804791


##Using Naive Bayes Algorithm

In [0]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[2634 1478]
 [ 249 1274]]
              precision    recall  f1-score   support

           0       0.91      0.64      0.75      4112
           1       0.46      0.84      0.60      1523

    accuracy                           0.69      5635
   macro avg       0.69      0.74      0.67      5635
weighted avg       0.79      0.69      0.71      5635

0.6935226264418811


##K nearest Neighbours

In [0]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[3945  167]
 [1168  355]]
              precision    recall  f1-score   support

           0       0.77      0.96      0.86      4112
           1       0.68      0.23      0.35      1523

    accuracy                           0.76      5635
   macro avg       0.73      0.60      0.60      5635
weighted avg       0.75      0.76      0.72      5635

0.7630878438331854


##Using SVM

In [0]:
from sklearn.svm import SVC
svm = SVC(kernel="linear",C=0.025,random_state=101)
svm.fit(X_train,y_train)
y_pred = svm.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[3669  443]
 [ 758  765]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      4112
           1       0.63      0.50      0.56      1523

    accuracy                           0.79      5635
   macro avg       0.73      0.70      0.71      5635
weighted avg       0.78      0.79      0.78      5635

0.7868677905944986
